name: CI
on: 
  push:
    branches: ["main"]

jobs:
  job1-call-docker-build-push:
    permissions:
        contents: read
        pull-requests: write
    secrets: inherit
    uses: ./.github/workflows/job-docker-build-push.yml