name: CI-CD

on: 
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-west-2
          aws-access-key-id: AKIAY4P52ZUQSR6ITTNX
          aws-secret-access-key: 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
       
      - name: Autentication of docker hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      
      - name: Construction of Docker's image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            renancoradini/denzelapp01:${{github.run_number}}
            renancoradini/denzelapp01:latest

  CD: 
  #  runs-on: ubuntu-latest
   # needs: [CI]

   # steps:
   # - users: